---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-claim
  namespace: ha
  labels:
    app: home-assistant
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi