---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: ha
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.0.111
spec:
  type: LoadBalancer
  selector:
    app: home-assistant
  ports:
    - protocol: TCP
      port: 8123
      targetPort: 8123