- name: Check if restart is required
  hosts: servers
  gather_facts: no
  remote_user: serveradmin
  become: true
  tasks:
    - name: Check that the reboot-required exists
      stat:
        path: /var/run/reboot-required
      register: p
    - debug:
        msg: "Reboot required"
      when: p.stat.exists